### PR TITLE
Skip static linking VSC creation if VS already exists

### PR DESCRIPTION
**Pull request by ashish-amarnath**
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

Fixes: #41 

This PR should be merged after #63

### CODE REVIEW

**Comment by ashish-amarnath** [comment]
hold for #63

**Comment by carlisia** [comment]
@nrb looks like this could be merged.

**Comment by nrb** [comment]
Looks like there are merge conflicts.

**Comment by ashish-amarnath** [comment]
Merge conflict resolved.

**Pull request merged**
