### PR TITLE
Rename files, structs and plugin registered names

### PR DESCRIPTION
**Pull request by ashish-amarnath**
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

Branch for this PR was cut from that of #36 
In this change:

- rename files to follow `<type>_action.go` and `<type>_action_test.go` naming scheme in `internal/backup` and `internal/restore` directories
- rename plugin structs to follow `<Type>BackupItemAction` and `<Type>RestoreItemAction` naming scheme
- follow `velero.io/csi-<type>-backupper` and `velero.io/csi-type-restorer` convention to register plugins

### CODE REVIEW

**Comment by nrb** [comment]
@ashish-amarnath Ready for a rebase!

**Comment by skriss** [comment]
standing by to review after rebase

**Comment by ashish-amarnath** [comment]
messed up the rebase and lost all the changes. Redoing the changes and will push here

**Comment by ashish-amarnath** [comment]
Didn't mean to close this PR . Will re-open once the changes are re-done

**Comment by ashish-amarnath** [comment]
I wasn't able to revive this PR. Opened a new one in its place #39 with the same set of (intended) changes.

**Pull request closed without merging**
